### Books Index
GET http://localhost:3000/books.json 

### Books Create
POST http://localhost:3000/books.json 
Content-Type: application/json

{
  "title": "Test title",
  "author": "Test author",
  "description": "test description",
  "language": "test language",
  "image": "https://i.redd.it/jeuusd992wd41.jpg"
}

### Books Show
GET http://localhost:3000/books/6.json 
Content-Type: application/json

### Books Update 
PATCH http://localhost:3000/books/7.json
Content-Type: application/json

{
  "title": "Test title!!!!!"
}

### Books Destroy
DELETE http://localhost:3000/books/6.json 